import { estimatePhases } from '../domain/lift-phases';
import type { VisionAnalysis } from '../domain/vision';
import { barMetrics } from '../domain/bar-track';
import { escapeHtml as e, icon } from './html';
export function movementPhases(a: VisionAnalysis, canSeek: boolean): string {
  const lift = a.lift ?? estimatePhases(a);
  return `<section class="real-phases" aria-label="Movement phases"><div class="section-title"><h2>Movement phases</h2><span class="micro">7 PHASES · ESTIMATED</span></div><div class="timeline measured-timeline">${lift.phases.map((p) => `<button data-cv-phase="${e(p.name)}" ${p.start === null ? '' : `data-cv-time="${p.start}"`} ${p.start === null || !canSeek ? 'disabled' : ''} aria-pressed="false"><span class="phase-line ${p.start === null ? 'unresolved' : ''}"></span><b>${p.start === null ? '—' : p.start.toFixed(2) + ' s'}</b><span>${e(p.name)}</span></button>`).join('')}</div><p class="footnote">${!a.lift && !a.frames.length ? 'This older summary has no phase data. Re-import the clip to analyze its phases.' : 'Pose-based estimates, not confirmed barbell events. Unresolved phases stay blank; no demo timings or scores are used.'} Timing resolution: approximately ${(1 / a.sampleRate).toFixed(2)} s.</p><div id="cv-phase-reading" class="selected-reading" aria-live="polite">Select an available phase to inspect that moment in your video.</div><details><summary>Phase evidence and timing</summary><dl class="phase-evidence">${lift.phases.map((p) => `<div><dt>${e(p.name)} · ${p.start === null ? 'Unresolved' : p.start.toFixed(2) + ' s'}</dt><dd>${e(p.evidence)}${p.end !== null && p.start !== null ? ` Duration: ${(p.end - p.start).toFixed(2)} s.` : ''}${p.coverage !== null ? ` Usable pose frames: ${Math.round(p.coverage * 100)}%.` : ''}</dd></div>`).join('')}</dl></details></section>`;
}
export function techniqueScore(a: VisionAnalysis): string {
  const lift = a.lift ?? estimatePhases(a);
  return `<aside class="tracking-score technique-check-score" aria-label="Experimental movement check score"><span class="micro">MOVEMENT CHECKS</span><div><b>${lift.score ?? '—'}</b><span>/ 100</span></div><p>${lift.score === null ? 'Full phase sequence required' : `${lift.checks.filter((c) => c.passed).length} of ${lift.checks.length} checks met`}<br><strong>Experimental · not a validated rating</strong></p></aside>`;
}
export function techniqueFeedback(a: VisionAnalysis, canSeek: boolean): string {
  const lift = a.lift ?? estimatePhases(a);
  return `<section aria-label="Technique observations"><div class="section-title"><h2>The details that matter</h2></div>${lift.checks.length ? lift.checks.map((c) => `<article class="measured-event"><button data-cv-time="${c.time}" ${canSeek ? '' : 'disabled'}><span>${e(c.name)}</span><b>${c.value}${e(c.unit)} ${icon('arrow')}</b></button><p>${e(c.detail)}</p><span class="event-kind">${c.passed ? 'CHECK MET' : 'REVIEW THIS MOMENT'} · EXPERIMENTAL THRESHOLD ≥${c.target}${e(c.unit)}</span>${!c.passed ? '<p>Review this frame with a coach before treating the threshold as a technique correction.</p>' : ''}</article>`).join('') : '<p class="notice">No technique score assigned. A complete, reliably tracked phase sequence and overhead recovery are required for the experimental movement checks.</p>'}<details><summary>How the score is calculated</summary><p class="footnote">Each of five visible-angle checks contributes 20 points: pull elbow ≥160°, end-of-pull hip and knee ≥165°, receiving elbow ≥165°, standing recovery knee ≥165°. These are transparent prototype rules, not validated coaching standards. Tracking coverage is separate. A 100 does not establish a good or successful lift; balance, bar path, timing and individual anatomy are not included.</p></details></section>`;
}
export function barPanel(a: VisionAnalysis, canTrack: boolean): string {
  const track = a.bar,
    metrics = track ? barMetrics(track) : null;
  const path =
    track?.points.map((p, i) => `${i ? 'L' : 'M'}${p.x},${p.y}`).join(' ') ??
    '';
  return `<section class="bar-section" aria-label="Measured bar path"><div class="section-title"><h2>Follow the bar</h2><span class="micro">${track ? 'CALIBRATED PLATE TRACK' : 'CALIBRATION REQUIRED'}</span></div>${track ? `<svg class="measured-bar-path" viewBox="0 0 ${track.width} ${track.height}" role="img" aria-label="Measured plate-center path over the tracked interval"><path d="${path}" fill="none" stroke="#d4f778" stroke-width="2"/></svg>` : ''}<dl class="bar-metrics"><div><dt>Horizontal displacement</dt><dd>${metrics ? metrics.horizontalCm.toFixed(1) + '<small> cm</small>' : '—'}</dd></div><div><dt>Vertical displacement</dt><dd>${metrics ? metrics.verticalM.toFixed(2) + '<small> m</small>' : '—'}</dd></div><div><dt>Peak upward velocity</dt><dd>${metrics?.peakVelocity !== null && metrics?.peakVelocity !== undefined ? metrics.peakVelocity.toFixed(2) + '<small> m/s</small>' : '—'}</dd></div></dl><p class="footnote">${track ? `Reviewed plate-center track · ${track.start.toFixed(2)}–${track.end.toFixed(2)} s · ${track.diameterCm} cm calibration. ${track.stoppedEarly ? 'Tracking stopped when confidence fell. Values cover only this partial interval.' : ''} Horizontal displacement is the greatest deviation from the first point; vertical displacement is the largest rise. Peak upward velocity is a sampled estimate, not instantaneous speed.` : 'Mark a visible plate and enter its real diameter to measure the bar. Wrist motion is never substituted for bar motion.'}</p>${canTrack ? '<button class="secondary" data-action="track-bar">' + (track ? 'Review / retrack bar' : 'Calibrate and track bar') + '</button>' : '<p class="footnote">Re-import the video to calibrate and track the bar.</p>'}</section>`;
}
