import { expect, it } from 'vitest';
import trace from '../fixtures/six-clean-trace.json';
import { analyzePoseSamples } from '../../src/domain/vision';
import { analyzeRepetitions } from '../../src/domain/repetitions';
const frames = trace.rows.map((row) => ({
  time: row[0] as number,
  people: row[1] as number,
  landmarks: (row[2] as number[][]).map((p) => ({
    x: p[0],
    y: p[1],
    visibility: p[2],
  })),
}));
const analysis = analyzePoseSamples(
  frames,
  trace.width,
  trace.height,
  trace.duration,
  trace.sampleRate,
  'auto',
);
const reps = analyzeRepetitions(analysis);
it('recognizes six cleans including the floor clean following the first lowering', () => {
  expect(reps).toHaveLength(6);
  expect(reps.slice(0, 2).map((r) => r.exercise?.id)).toEqual([
    'clean',
    'clean',
  ]);
  expect(reps.every((r) => r.exercise?.id?.includes('clean'))).toBe(true);
});
it('does not score preparation as explosive extension', () => {
  // Broad windows from visual review, not labels generated by the analyzer.
  const windows = [
    [2.3, 3.3],
    [6.9, 8],
    [11.4, 12.2],
    [13.9, 14.5],
    [17.8, 18.8],
    [22.7, 23.6],
  ];
  reps.forEach((r, i) => {
    const start = r.lift!.phases.find(
      (p) => p.name === (i < 2 ? 'First pull' : 'Second pull'),
    )!.start!;
    expect(start).toBeGreaterThanOrEqual(windows[i][0]);
    expect(start).toBeLessThanOrEqual(windows[i][1]);
    for (const c of r.lift!.checks.filter(
      (c) => c.name === 'Hip extension' || c.name === 'Knee extension',
    ))
      expect(c.time).toBeGreaterThanOrEqual(windows[i][0]);
  });
});
it('does not report recovery during the final squat descent', () => {
  const recovery = reps[5].lift!.phases[6].start;
  expect(recovery === null || recovery >= 24.5).toBe(true);
});
